
public class ExceptionTest3 {
	public static void main(String[] args) throws Exception {
//		try {
			throw new Exception("예외 발생"); 
//		}catch (Exception e) {
//			//e.printStackTrace();
//			System.out.println(e.getMessage());
//		}
		
	}
}
